server:
  port: 8081
application:
  kafka:
    edit-event-notification-topic: "edit-event-notification-topic"
    nearest-events-notification-topic: "nearest-events-notification-topic"
  mock-mail-service-enabled: true

spring:
  kafka:
    consumer:
      group-id: "mail-group"
      bootstrap-servers: "localhost:9092"
      client-id: "event-notification-consumer"
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "org.dgp.eventmanager.notifications"
  mail:
    host: smtp.yandex.ru
    port: 465
    username: dimgeo@yandex.ru
    password: mhebkqgcftrvvfmu
    debug: true


logging:
  level:
    ROOT: INFO